spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.70.85:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: ENC(4VOMKgt6rq2oyZp3ZmM4cLae6IEJvDsNR93JQSkdYUHE+l625cSucf4VdtXUn5ow)
    password: ENC(2Di/wKAZi3LtTUlYIlnDOi174XlKMX1pLZPQ3gVmU6ajF0Bw4b/47hhw4gJOfByE)
    initial-size: 8
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-on-borrow: true
    test-on-return: false
    pool-prepared-statements: true
    #      # 配置监控拦截的filters 去掉后监控sql无法统计 wall 防火墙
    filters: stat,wall
    max-pool-prepared-statement-per-connection-size: 25
    use-global-data-source-stat: true
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlmillis=500