spring:
  redis:
    host: 39.106.70.85
    database: 1
    port: 6379
    password:
    timeout: 5000ms
    lettuce:
      pool:
        max-idle: 2000
        max-active: 10
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 500ms