spring:
  application:
    name: demo
  resources:
    static-locations: classpath:/static/,classpath:/resources/
  profiles:
    active: pro,datasource,jasypt,log,mybatis,pagehelper,rabbitmq,redis,swagger
  boot:
    admin:
      client:
        url: http://localhost:8081
        username: admin
        password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  servlet:
    context-path: /api/

rong:
  TEMPLATE_ID: dbVeHPNx41jaeiyhFNBaZX
  REGION: 86
  SEND_CODE_URL: http://api.sms.ronghub.com/sendCode.json
  APP_SECRIT: BEV264hUatgD
  APP_KEY: mgb7ka1nmddyg
  VERIF_CODE_URL: http://api.sms.ronghub.com/verifyCode.json


