spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://47.104.62.154:3306/store-education?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: root
    password: 123456
  redis:
    host: 47.104.62.154
    database: 2
    port: 6379
    password: mypass
    timeout: 1000ms
    lettuce:
      pool:
        max-idle: 2000
        max-active: 10
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 500ms

server:
  port: 8088