spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://39.106.70.85:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: ENC(4VOMKgt6rq2oyZp3ZmM4cLae6IEJvDsNR93JQSkdYUHE+l625cSucf4VdtXUn5ow)
    password: ENC(2Di/wKAZi3LtTUlYIlnDOi174XlKMX1pLZPQ3gVmU6ajF0Bw4b/47hhw4gJOfByE)

  rabbitmq:
    host: 39.106.70.85
    username: admin
    password: admin
    port: 5672

  redis:
    host: 39.106.70.85
    database: 1
    port: 6379
    password:
    timeout: 5000ms
    lettuce:
      pool:
        max-idle: 2000
        max-active: 10
        max-wait: -1ms
        min-idle: 0

server:
  port: 8081
