spring:
  application:
    name: demo
  resources:
    static-locations: classpath:/static/,classpath:/resources/
  profiles:
    active: pro
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 8
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-on-borrow: true
    test-on-return: false
    pool-prepared-statements: true
    #      # 配置监控拦截的filters 去掉后监控sql无法统计 wall 防火墙
    filters: stat,wall
    max-pool-prepared-statement-per-connection-size: 25
    use-global-data-source-stat: true
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlmillis=500

swagger:
  enabled: true
  title: API
  version: V1.0
  basePackage: com.example.web.controller
  description: This document describes the definition of the front-end system microservice interface
  terms-of-service-url: https://swagger.io/
  license-url: http://www.apache.org/licenses/LICENSE-2.0

mybatis:
  type-aliases-package: com.hc.business.model
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

jasypt:
  encryptor:
    bean: encryptorBean

server:
  servlet:
    context-path: /api/

rong:
  TEMPLATE_ID: dbVeHPNx41jaeiyhFNBaZX
  REGION: 86
  SEND_CODE_URL: http://api.sms.ronghub.com/sendCode.json
  APP_SECRIT: BEV264hUatgD
  APP_KEY: mgb7ka1nmddyg
  VERIF_CODE_URL: http://api.sms.ronghub.com/verifyCode.json

logging:
  file:
    path: /spring/log